# Generated by Django 5.2.15 on 2026-06-08 08:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_mealplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedrecipe',
            name='share_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
