# Generated by Django 5.2.15 on 2026-06-18 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_recipehistory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='macrolog',
            old_name='carbs_g',
            new_name='carbs',
        ),
        migrations.RenameField(
            model_name='macrolog',
            old_name='fats_g',
            new_name='fats',
        ),
        migrations.RenameField(
            model_name='macrolog',
            old_name='protein_g',
            new_name='protein',
        ),
    ]
