# Generated by Django 5.2.15 on 2026-06-21 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_rename_carbs_g_macrolog_carbs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='premium_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='premium_start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='razorpay_subscription_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
